[config]

[templates.niri-ring-override]
input_path = '~/.config/matugen/templates/niri-ring-override.kdl'
output_path = '~/.config/niri/dms/ring-override.kdl'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'
