# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e5e1e3"

# Title color for boxes
theme[title]="#c6c5d6"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#c8c5cd"

# Background color of selected item in processes box
theme[selected_bg]="#c6c5d6"

# Foreground color of selected item in processes box
theme[selected_fg]="#2f2f3d"

# Color of inactive/disabled text
theme[inactive_fg]="#c8c5cc"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#d3c5ab"

# Cpu box outline color
theme[cpu_box]="#919096"

# Memory/disks box outline color
theme[mem_box]="#919096"

# Net up/down box outline color
theme[net_box]="#919096"

# Processes box outline color
theme[proc_box]="#919096"

# Box divider line and small boxes line color
theme[div_line]="#47464c"

# Temperature graph colors
theme[temp_start]="#c8c5cd"
theme[temp_mid]="#c6c5d6"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#c8c5cd"
theme[cpu_mid]="#c6c5d6"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#c8c5cd"
theme[free_mid]=""
theme[free_end]="#4b4b51"

# Mem/Disk cached meter
theme[cached_start]="#d3c5ab"
theme[cached_mid]=""
theme[cached_end]="#726751"

# Mem/Disk available meter
theme[available_start]="#c6c5d6"
theme[available_mid]=""
theme[available_end]="#676776"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#c8c5cd"
theme[download_mid]="#c6c5d6"
theme[download_end]="#d3c5ab"

# Upload graph colors
theme[upload_start]="#c8c5cd"
theme[upload_mid]="#c6c5d6"
theme[upload_end]="#d3c5ab"
