cursor #e5e1e3
cursor_text_color #c8c5cc

foreground            #e5e1e3
background            #141314
selection_foreground  #303036
selection_background  #c8c5cd
url_color             #c6c5d6

color0   #141314
color1   #f66e8e
color2   #6bd67f
color3   #ffd872
color4   #b9b7cb
color5   #555463
color6   #c6c5d6
color7   #d4d3e0
color8   #81808b
color9   #ff9fb5
color10  #a5ffb6
color11  #ffe6a5
color12  #dcdbeb
color13  #f1f0ff
color14  #f6f5ff
color15  #f9f8ff
